### ISSUE TITLE
Compatible with phone / message app ?

### ISSUE THREAD

**Issue by Jeje292** [reiryuki/Features-of-Google-App-Magisk-Module#1]
Hello,

OS : Lineageos 19.1 (Android 12L, september security patch)
Magisk : 27.0
Installed module : GoogleApp-ARM64-Min29-MagiskModule-20240903015918.zip

I successfully installed and used Google Assistant (Thank you !), but I can't make phone call, the app search on Google instead of make call.
For test, I installed Google Phone app & contact without changes.
I can't send SMS too through OK Google or Hey Google.

Any tips to make this work ?

I wanted to join Telegram channel but banned less one minute later after join (I don't know why... stress anti bot mod maybe ?)

Edit : I successfully reach to join Telegram group and sent a DM to Rei Ryuki, so I think it's useless to keep this discussion open

Regards

**Comment by reiryuki** [comment]
Support & Bug Report
https://t.me/androidryukimodsdiscussions/2618
If you don't do above, issues will be closed immediately
